spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/berryweb_user
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api

app:
  jwt:
    secret: ${JWT_SECRET:myVeryLongSecretKeyThatIsAtLeast32BytesLongForJWTSigning}
    expiration: ${JWT_EXPIRATION:86400} # 24 hours in seconds

  security:
    max-login-attempts: ${MAX_LOGIN_ATTEMPTS:5}
    account-lock-time: ${ACCOUNT_LOCK_TIME:3600} # 1 hour in seconds
    password-reset-token-expiration: ${PASSWORD_RESET_EXPIRATION:3600} # 1 hour
    email-verification-token-expiration: ${EMAIL_VERIFICATION_EXPIRATION:86400} # 24 hours
    session-timeout: ${SESSION_TIMEOUT:7200} # 2 hours

logging:
  level:
    com.berryweb: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:INFO}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized